DROP TABLE IF EXISTS work_order_activities;
DROP TABLE IF EXISTS work_orders;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    customer_name VARCHAR(120) NOT NULL,
    assignee VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_work_order_status CHECK (status IN ('RECEIVED', 'IN_PROGRESS', 'DONE', 'CANCELLED'))
);

CREATE TABLE work_order_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    actor VARCHAR(100) NOT NULL,
    action VARCHAR(40) NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30),
    detail VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_order_activity_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT chk_work_order_activity_action CHECK (action IN ('CREATED', 'STATUS_CHANGED'))
);

CREATE INDEX idx_work_orders_status ON work_orders(status);
CREATE INDEX idx_work_orders_updated_at ON work_orders(updated_at);
CREATE INDEX idx_work_order_activities_order ON work_order_activities(work_order_id);
CREATE INDEX idx_work_order_activities_created_at ON work_order_activities(created_at);
