DROP TABLE IF EXISTS work_order_approvals;
DROP TABLE IF EXISTS work_order_activities;
DROP TABLE IF EXISTS work_orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(120) NOT NULL,
    contact_name VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_customer_status CHECK (status IN ('LEAD', 'ACTIVE', 'INACTIVE'))
);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    customer_id BIGINT NOT NULL,
    assignee VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    due_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT chk_work_order_status CHECK (status IN ('RECEIVED', 'IN_PROGRESS', 'WAITING_APPROVAL', 'APPROVED', 'DONE', 'CANCELLED')),
    CONSTRAINT chk_work_order_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT'))
);

CREATE TABLE work_order_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    actor VARCHAR(100) NOT NULL,
    action VARCHAR(40) NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30),
    detail VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_work_order_activity_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT chk_work_order_activity_action CHECK (action IN ('CREATED', 'STATUS_CHANGED', 'APPROVAL_REQUESTED', 'APPROVED', 'REJECTED'))
);

CREATE TABLE work_order_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    requested_by VARCHAR(100) NOT NULL,
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_comment VARCHAR(500),
    decision VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    decided_by VARCHAR(100),
    decided_at TIMESTAMP,
    decision_comment VARCHAR(500),
    CONSTRAINT fk_work_order_approval_order FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE CASCADE,
    CONSTRAINT chk_work_order_approval_decision CHECK (decision IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX idx_customers_status ON customers(status);
CREATE INDEX idx_customers_company_name ON customers(company_name);
CREATE INDEX idx_work_orders_customer ON work_orders(customer_id);
CREATE INDEX idx_work_orders_status ON work_orders(status);
CREATE INDEX idx_work_orders_priority ON work_orders(priority);
CREATE INDEX idx_work_orders_due_date ON work_orders(due_date);
CREATE INDEX idx_work_orders_updated_at ON work_orders(updated_at);
CREATE INDEX idx_work_order_activities_order ON work_order_activities(work_order_id);
CREATE INDEX idx_work_order_activities_created_at ON work_order_activities(created_at);
CREATE INDEX idx_work_order_approvals_order ON work_order_approvals(work_order_id);
CREATE INDEX idx_work_order_approvals_decision ON work_order_approvals(decision);
CREATE INDEX idx_work_order_approvals_requested_at ON work_order_approvals(requested_at);
